#!/usr/bin/env bash
set -euo pipefail

DOTFILES="$HOME/dotfiles"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

MAC_LINKS=(
    npm clang opencode fastfetch bat
    karabiner nvim yazi wget prettier git lazygit doom tmux
)

LINUX_LINKS=(
    nvim git
)

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

log() { echo -e "${GREEN}==>${NC} $1"; }
warn() { echo -e "${YELLOW}⚠${NC}  $1"; }
error() {
    echo -e "${RED}✖${NC}  $1" >&2
    exit 1
}

if [[ "$OSTYPE" == darwin* ]]; then
    echo "[macOS] Linking configs..."
    rm -rf "${HOME:?}/bin"
    ln -sfnv "${DOTFILES:?}/bin" "${HOME:?}/bin"
    export PATH="$PATH:$HOME/bin"
    LINKS=("${MAC_LINKS[@]}")

elif [[ "$OSTYPE" == linux-* ]]; then
    echo "[Linux] Linking configs..."
    rm -rf "${HOME:?}/bin"
    ln -sfnv "$DOTFILES/bin" "$HOME/bin"
    export PATH="$PATH:$HOME/bin"
    LINKS=("${LINUX_LINKS[@]}")

else
    echo "Unsupported OS: $OSTYPE"
    exit 1
fi

for dir in "${LINKS[@]}"; do
    src="$DOTFILES/$dir"
    target="$XDG_CONFIG_HOME/$dir"

    [ -e "$target" ] && rm -rf "$target"
    ln -sfnv "$src" "$target"
done

# shared configs
ln -sfnv "$DOTFILES/starship/starship.toml" "$XDG_CONFIG_HOME/starship.toml"

ln -sfnv "$DOTFILES/tmux/.tmux.conf" "$HOME/.tmux.conf"
ln -sfnv "$DOTFILES/tmux/.config/tmux" "$XDG_CONFIG_HOME/tmux"

ln -sfnv "$DOTFILES/zsh/.zshenv" "$HOME/.zshenv"
ln -sfnv "$DOTFILES/zsh/.config/zsh" "$XDG_CONFIG_HOME/zsh"

mkdir -pv "${HISTDIR:-$HOME/.local/share/history}"
