#!/usr/bin/env bash

path="$1"
home="${HOME%/}"
if [[ -n "$home" && "$path" == "$home" ]]; then
    path="~"
elif [[ -n "$home" && "$path" == "$home"/* ]]; then
    path="~/${path#$home/}"
fi

if [ "$path" = "~" ] || [ "$path" = "/" ]; then
    echo -n "$path"
    exit
fi

IFS='/' read -ra parts <<< "$path"
result=""
last=$(( ${#parts[@]} - 1 ))

for i in "${!parts[@]}"; do
    part="${parts[$i]}"
    if [ "$i" -eq "$last" ]; then
        result+="$part"
    elif [ "$part" = "~" ]; then
        result+="~/"
    elif [ -n "$part" ]; then
        result+="${part:0:1}/"
    else
        result+="/"
    fi
done

echo -n "$result"
